---
- hosts: confd-host
  vars:
    src: /src/confd/confd-0.5.0-darwin-amd64
    src_dir: /data/src
  remote_user: wangting
  sudo: yes
  tasks:
  - name: copy confd source
    sudo: true
    copy: src={{ src }} dest={{ src_dir }}/confd
  - name: make confd executalbe
    sudo: true
    file: path={{ src_dir }}/confd mode=0755
