---
- hosts: consul-host
  vars:
    src: /src/consul/0.4.0_linux_amd64.zip
    src_dir: /data/src
  remote_user: wangting
  sudo: yes
  tasks:
  - name: copy an unarchive consul
    unarchive: src={{ src }} dest={{ src_dir }}
