---
- hosts: etcd-host
  vars:
    src: /src/etcd/etcd-v0.4.6-linux-amd64.tar.gz
    src_dir: /data/src
  remote_user: wangting
  sudo: yes
  tasks:
  - name: create dest directory
    sudo: true
    file: path={{ src_dir }}/etcd state=directory
  - name: copy etc source
    sudo: true
    unarchive: src={{ src }} dest={{ src_dir }}/etcd 
